'''
Copyright 2021 Flexera Software LLC
See LICENSE.TXT for full license text
SPDX-License-Identifier: MIT

Author : sgeary  
Created On : Tue Dec 21 2021
File : common_licenses.py
'''

commonLicenses = {}
commonLicenses["1"] = ["LGPL-2.1", "GNU Lesser General Public License v2.1 only"]
commonLicenses["2"] = ["Artistic-1.0", "Artistic License 1.0"]
commonLicenses["5"] = ["Apache-1.1", "Apache License 1.1"]
commonLicenses["6"] = ["CPL-1.0", "Common Public License 1.0"]
commonLicenses["11"] = ["MPL-1.1", "Mozilla Public License 1.1"]
commonLicenses["13"] = ["MPL-1.0", "Mozilla Public License 1.0"]
commonLicenses["20"] = ["Apache-2.0", "Apache License 2.0"]
commonLicenses["46"] = ["EPL-1.0" ,"Eclipse Public License 1.0"]
commonLicenses["48"] = ["CDDL-1.0", "Common Development and Distribution License 1.0"]
commonLicenses["137"] = ["ANTLR-PD", "ANTLR Software Rights Notice"]
commonLicenses["197"] = ["GPL-3.0", "GNU General Public License v3.0 only"]
commonLicenses["199"] = ["LGPL-2.0", "GNU Library General Public License v2 only"]
commonLicenses["216"] = ["LGPL-3.0", "GNU Lesser General Public License v3.0 only"]
commonLicenses["229"] = ["AGPL-3.0", "GNU Affero General Public License v3.0"]
commonLicenses["331"] = ["GPL-2.0", "GNU General Public License v2.0 only"]
commonLicenses["334"] = ["CPAL-1.0", "Common Public Attribution License 1.0"]
commonLicenses["335"] = ["CC-BY-SA-2.0", "Creative Commons Attribution Share Alike 2.0 Generic"]
commonLicenses["343"] = ["GPL-1.0", "GNU General Public License v1.0 only"]
commonLicenses["350"] = ["Artistic-2.0", "Artistic License 2.0"]
commonLicenses["352"] = ["MS-RL", "Microsoft Reciprocal License"]
commonLicenses["361"] = ["CC-BY-NC-SA-3.0", "Creative Commons Attribution Non Commercial Share Alike 3.0 Unported"]
commonLicenses["384"] = ["MS-PL", "Microsoft Public License"]
commonLicenses["394"] = ["CC-BY-2.5", "Creative Commons Attribution 2.5 Generic"]
commonLicenses["415"] = ["CC-BY-3.0", "Creative Commons Attribution 3.0 Unported"]
commonLicenses["431"] = ["CC-BY-NC-ND-3.0", "Creative Commons Attribution Non Commercial No Derivatives 3.0 Unported"]
commonLicenses["542"] = ["CC-BY-NC-3.0", "Creative Commons Attribution Non Commercial 3.0 Unported"]
commonLicenses["572"] = ["CC-BY-1.0", "Creative Commons Attribution 1.0 Generic"]
commonLicenses["573"] = ["CC-BY-2.0", "Creative Commons Attribution 2.0 Generic"]
commonLicenses["574"] = ["CC-BY-ND-1.0", "Creative Commons Attribution No Derivatives 1.0 Generic"]
commonLicenses["575"] = ["CC-BY-ND-2.0", "Creative Commons Attribution No Derivatives 2.0 Generic"]
commonLicenses["576"] = ["CC-BY-ND-2.5", "Creative Commons Attribution No Derivatives 2.5 Generic"]
commonLicenses["577"] = ["CC-BY-ND-3.0", "Creative Commons Attribution No Derivatives 3.0 Unported"]
commonLicenses["578"] = ["CC-BY-NC-1.0", "Creative Commons Attribution Non Commercial 1.0 Generic"]
commonLicenses["579"] = ["CC-BY-NC-2.0", "Creative Commons Attribution Non Commercial 2.0 Generic"]
commonLicenses["580"] = ["CC-BY-NC-2.5", "Creative Commons Attribution Non Commercial 2.5 Generic"]
commonLicenses["581"] = ["CC-BY-NC-ND-2.0", "Creative Commons Attribution Non Commercial No Derivatives 2.0 Generic"]
commonLicenses["582"] = ["CC-BY-NC-ND-2.5", "Creative Commons Attribution Non Commercial No Derivatives 2.5 Generic"]
commonLicenses["583"] = ["CC-BY-NC-SA-1.0", "Creative Commons Attribution Non Commercial Share Alike 1.0 Generic"]
commonLicenses["584"] = ["CC-BY-NC-SA-2.0", "Creative Commons Attribution Non Commercial Share Alike 2.0 Generic"]
commonLicenses["585"] = ["CC-BY-NC-SA-2.5", "Creative Commons Attribution Non Commercial Share Alike 2.5 Generic"]
commonLicenses["586"] = ["CC-BY-SA-1.0", "Creative Commons Attribution Share Alike 1.0 Generic"]
commonLicenses["587"] = ["CC-BY-SA-2.5", "Creative Commons Attribution Share Alike 2.5 Generic"]
commonLicenses["662"] = ["GPL-2.0-with-autoconf-exception", "GNU General Public License v2.0 w/Autoconf exception"]
commonLicenses["664"] = ["GPL-3.0-with-autoconf-exception", "GNU General Public License v3.0 w/Autoconf exception"]
commonLicenses["665"] = ["GPL-2.0-with-bison-exception", "GNU General Public License v2.0 w/Bison exception"]
commonLicenses["669"] = ["GPL-2.0-with-classpath-exception", "GNU General Public License v2.0 w/Classpath exception"]
commonLicenses["670"] = ["CDDL-1.1", "Common Development and Distribution License 1.1"]
commonLicenses["688"] = ["Apache-1.0", "Apache License 1.0"]
commonLicenses["693"] = ["CC-BY-NC-ND-1.0", "Creative Commons Attribution Non Commercial No Derivatives 1.0 Generic"]
commonLicenses["694"] = ["CC-BY-SA-3.0", "Creative Commons Attribution Share Alike 3.0 Unported"]
commonLicenses["698"] = ["GPL-1.0+", "GNU General Public License v1.0 or later"]
commonLicenses["699"] = ["GPL-2.0+", "GNU General Public License v2.0 or later"]
commonLicenses["700"] = ["GPL-2.0-with-font-exception", "GNU General Public License v2.0 w/Font exception"]
commonLicenses["701"] = ["GPL-2.0-with-GCC-exception", "GNU General Public License v2.0 w/GCC Runtime Library exception"]
commonLicenses["702"] = ["GPL-3.0+", "GNU General Public License v3.0 or later"]
commonLicenses["703"] = ["GPL-3.0-with-GCC-exception", "GNU General Public License v3.0 w/GCC Runtime Library exception"]
commonLicenses["704"] = ["LGPL-2.1+", "GNU Library General Public License v2.1 or later"]
commonLicenses["705"] = ["LGPL-3.0+", "GNU Lesser General Public License v3.0 or later"]
commonLicenses["706"] = ["LGPL-2.0+", "GNU Library General Public License v2 or later"]
commonLicenses["733"] = ["Zlib", "zlib License"]
commonLicenses["807"] = ["CPOL-1.02", "Code Project Open License 1.02"]
commonLicenses["1201"] = ["MPL-2.0", "Mozilla Public License 2.0"]
commonLicenses["1461"] = ["WTFPL", "Do What The F*ck You Want To Public License"]
commonLicenses["1505"] = ["Artistic-1.0-Perl", "Artistic License 1.0 (Perl)"]
commonLicenses["1512"] = ["CC-BY-4.0", "Creative Commons Attribution 4.0 International"]
commonLicenses["1513"] = ["CC-BY-NC-ND-4.0", "Creative Commons Attribution Non Commercial No Derivatives 4.0 International"]
commonLicenses["1514"] = ["CC-BY-ND-4.0", "Creative Commons Attribution No Derivatives 4.0 International"]
commonLicenses["1515"] = ["CC-BY-NC-SA-4.0", "Creative Commons Attribution Non Commercial Share Alike 4.0 International"]
commonLicenses["1516"] = ["CC-BY-NC-4.0", "Creative Commons Attribution Non Commercial 4.0 International"]
commonLicenses["1517"] = ["CC-BY-SA-4.0", "Creative Commons Attribution Share Alike 4.0 International"]
commonLicenses["1654"] = ["AGPL-1.0", "Affero General Public License v1.0"]
commonLicenses["1911"] = ["EPL-2.0", "Eclipse Public License 2.0"]
